version: '3'
services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}"
  fastapi:
    image: anisongdb-api:${ANISONGDB_API_VERSION}
    ports:
      - ${ANISONGDB_API_PORT}
    depends_on:
      - redis
    env_file:
      - .docker.env